{% set name = "usgscsm" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    url: https://github.com/DOI-USGS/{{ name }}/archive/{{ version }}.tar.gz
    sha256: a8ae036caa0b958fa6e28ee8ba7a29c2b6fefeb1413144243d59521f51d1dc12

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make
  host:
    - csm
    - ale
    - nlohmann_json
    - eigen
    - vc  # [win]
    - proj =9.3.0
  run:
    - ale
    - {{ pin_compatible('nlohmann_json', min_pin='x.x', max_pin='x.x') }}
    - csm
    - eigen
    - {{ pin_compatible('proj', min_pin='x.x', max_pin='x.x') }}

test:
  commands:
    - test -e $PREFIX/lib/csmplugins/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/DOI-USGS/usgscsm
  license: CC0-1.0
  license_file: LICENSE.md
  summary: USGS Astrogeology developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/DOI-USGS/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - acpaquette
    - chkim-usgs
    - Kelvinrr
