{% set name = "usgscsm" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4a60490399c44de5818e4ae49cd941b03b42cf78464fa84fb0a8ed35f52603c5
  patches:
    - patches/0001-Fixing-json-version-ABI.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make
  host:
    - csm
    - ale
    - nlohmann_json
    - eigen
    - vc  # [win]
  run:
    - ale
    - {{ pin_compatible('nlohmann_json', min_pin='x.x', max_pin='x.x') }}
    - csm
    - eigen

test:
  commands:
    - test -e $PREFIX/lib/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/USGS-Astrogeology/usgscsm
  license: CC0-1.0
  license_file: LICENSE.md
  summary: USGS Astrogeolgoy developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/USGS-Astrogeology/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
    - acpaquette
