{% set name = "usgscsm" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    url: https://github.com/DOI-USGS/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 076cb97e59cd3fff86447d91572397d9cca04290e3a36d44844b0978306451e3

  # submodules
  - folder: ale
    url: https://github.com/DOI-USGS/ale/archive/0.10.0.zip
    sha256: 2373e0e1ff3715adef60e61db22e6cea1d5b7941f5b1999dd202065d3d84efb2
  - folder: csm
    url: https://github.com/USGS-Astrogeology/csm/archive/c78dbba3731432249a75db9fdd7415b292d46715.zip
    sha256: e3eb35fbc27df94d6432c66a93b1dd140a9e93d6897c9107d5a99ab0557e99ea
  - folder: gtest
    url: https://github.com/google/googletest/archive/aee0f9d9b5b87796ee8a0ab26b7587ec30e8858e.zip
    sha256: 04a1751f94244307cebe695a69cc945f9387a80b0ef1af21394a490697c5c895
  - folder: json
    url: https://github.com/nlohmann/json/archive/refs/tags/v3.8.0.zip
    sha256: 83947cb78d50990b4b931b8dbc8632781bc601baa45b75ece0899c7b98d86c0b
  - folder: ale/eigen
    url: https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
    sha256: eba3f3d414d2f8cba2919c78ec6daab08fc71ba2ba4ae502b7e5d4d99fc02cda
  - folder: PROJ
    url: https://github.com/OSGeo/PROJ/archive/9.3.1.zip
    sha256: 5bb137beba7c28d46898d358fc74ef57d18a80f56066a51ee467d3b48e9d69fa

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.10,<4.0.0
    - make
  host:
    - vc  # [win]
    - sqlite 3.46.0  # [linux]

  run:
    - vc  # [win]
    - sqlite 3.46.0  # [linux]

test:
  commands:
    - test -e $PREFIX/lib/csmplugins/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/DOI-USGS/usgscsm
  license: CC0-1.0
  license_file: LICENSE.md
  summary: USGS Astrogeology developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/DOI-USGS/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - acpaquette
    - chkim-usgs
    - Kelvinrr
