{% set name = "usgscsm" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1fbab354ca400841aa3e3e29cf223eeca27d27d195606b1fa28c7fdbb69f47ae

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
  host:
    - csm
    - vc  # [win]
  run:
    - csm

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - test -e $PREFIX/lib/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/USGS-Astrogeology/usgscsm
  license: Public Domain
  license_file: license.txt
  summary: USGS Astrogeolgoy developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/USGS-Astrogeology/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
